name: Deploy deb/rpm to s3 repo
on:
  push:
    branches: main
  pull_request: {}
  workflow_dispatch:
jobs:
  pkgs:
    name: ${{ matrix.pkg }}
    strategy:
      fail-fast: false
      matrix:
        pkg: [deb, rpm]
    environment: aws
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python 3.14
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"
    - name: Install deps
      run: pip install docker

    - name: Read DVC version
      run: echo "DVC_VERSION=$(<dvc_version.txt)" >> "$GITHUB_ENV"
    - name: Checkout specific version of dvc
      uses: actions/checkout@v6
      with:
          repository: treeverse/dvc
          ref: ${{ env.DVC_VERSION }}
          path: dvc
          persist-credentials: false
          fetch-depth: 0

    - name: Build and sign
      run: ./main.py build ${{ matrix.pkg }}
    - name: sanity check
      run: ./main.py test ${{ matrix.pkg }}
    - uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-region: us-east-2
        role-to-assume: arn:aws:iam::977611293394:role/dvc-s3-repo-deploy-${{ matrix.pkg }}
    - name: Upload
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, 'updated dvc to') }}
      env:
        GPG_ITERATIVE_ASC: ${{ secrets.GPG_ITERATIVE_ASC }}
        GPG_ITERATIVE_PASS: ${{ secrets.GPG_ITERATIVE_PASS }}
        AWS_S3_BUCKET: dvc-packages
        AWS_S3_PREFIX: ${{ matrix.pkg }}
      run: ./main.py upload ${{ matrix.pkg }}

  notify:
    if: github.ref == 'refs/heads/main' && failure()
    needs: [pkgs]
    runs-on: ubuntu-latest
    steps:
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.3.3
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: 'Package build failed for ${{ github.repository }}'
        SLACK_TITLE: CI Status
        SLACK_USERNAME: dvc-pkg-build
